### ISSUE TITLE
Read annotation format into Shapely objects

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/slidescore-api#1]
**Is your feature request related to a problem? Please describe.**
The annotation output of SlideScore has to be parsed into proper objects.

**Describe the solution you'd like**
Export objects into Shapely objects (or similar).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AjeyPaiK** [comment]
This feature has now been implemented in #5.
