### ISSUE TITLE
No shapely annotations

### ISSUE THREAD

**Issue by rharkes** [NKI-AI/slidescore-api#16]
**Describe the bug**
When getting annotations with shapely I get 0kb .json files.

**To Reproduce**
My study with ID 1764 has 100 cases with 3 slides per case. If you try to get annotations using `-o JSON` I get 300 .json files in the output folder. If I try with `-o SHAPELY` I get a folder structure, but it contains .json files of 0kb

**Expected behavior**
.json files with the annotations for each slide.

**Environment**
SlideScore Python API version: 0.1.0
How installed: pip
Python version: 3.9
Operating System: windows 10

**Additional context**
I discussed this issue with Ajey on teams.

**Comment by AjeyPaiK** [comment]
Thanks Rolf for finding this bug in your use case. Currently, the shapely annotations are downloaded with the assumption that there is only one slide per case and hence, one annotation. 

I will work on improving this to include multiple slides. 

Great catch!

**Comment by rharkes** [comment]
Thanks. I just cloned the repository and tried to reproduce the error in a clean venv, but suddenly there was no error anymore. The .json files were there. 

In my old environment I can still reproduce the error.

**Comment by AjeyPaiK** [comment]
Ah, it was probably an older version of the repository! Good to know!
