### ISSUE TITLE
Make the downloaded Shapely annotations compliant to open with QuPath. 

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/slidescore-api#17]
Problem:
Currently, the shapely objects that get downloaded by using the download-label tools of the api does not open in QuPath. 

Solution:
Change the saving format of the shapely polygons and make them adhere to the geojson format. 

**Additional context**
Rolf found a use case in his image analysis work where he wanted to use this interface to download some annotations and visualize them on QuPath.

**Comment by jonasteuwen** [comment]
If you do this make sure it's working in dlup too @AjeyPaiK
