### ISSUE TITLE
Broken when not specifying an output type to download-labels

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/slidescore-api#19]
Without -o the download-labels does not work

**Comment by AjeyPaiK** [comment]
The current design asks the user how they want to store the annotations after downloading them... one of JSON, RAW or Shapely. I think we need to handle this case better when the user doesn't specify the output formats. Maybe an error or a warning?

**Comment by AjeyPaiK** [comment]
Ah! nice! :) Thank you
