### ISSUE TITLE
io.UnsupportedOperation: not writable

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/slidescore-api#4]
**Describe the bug**
json.dump fails while writing annotations to file.

**To Reproduce**
(I have access to study 638)
slidescore -s 638 download-labels ~/junk/

**Expected behavior**
The cli must write annotations for each file in study 638 as json in the directory named ~/junk/

**Environment**
SlideScore Python API version: 0.1.0
How installed: Installed the CLI from repo.
Python version: 3.8.12
Operating System: Ubuntu 20.04.3 LTS

![Capture](https://user-images.githubusercontent.com/26798611/146572013-aececbf4-8e45-49a8-ab73-5bef99a5b05b.PNG)
.

**Comment by jonasteuwen** [comment]
What is precisely the reason it fails? Seems just like your folder is not writeable.

**Comment by AjeyPaiK** [comment]
Well, I got the bug when the file was opened without a mode in download_labels(). It was a simple bug.

        Before - `with open(save_dir / f"{image_id}.json") as file:`
        Now - `with open(save_dir / f"{image_id}.json", "w") as file:`

**Comment by jonasteuwen** [comment]
Seems to be fixed @AjeyPaiK ?

**Comment by AjeyPaiK** [comment]
Yes, this is fixed.

**Comment by AjeyPaiK** [comment]
It is addressed in #5
